dist: xenial
language: go

go:
  - "1.14.x"
  - "1.13.x"
  - "1.12.x"

script:
  - go test -v ./...
  - go build ./cmd/specious-bench
  - ./bench.sh ./specious-bench -entries 10000

addons:
  apt:
    packages:
      - libleveldb-dev
      - libleveldb1v5
