dist: xenial
language: go

go:
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"

script:
  - go test -v ./...
  - go build ./cmd/specious-bench
  - ./bench.sh ./specious-bench -entries 10000
  - ./loc.sh

addons:
  apt:
    packages:
      - libleveldb-dev
      - libleveldb1v5
      - cloc
