dist: xenial
language: go

go:
  - "1.10.x"
  - "1.11.x"

install:
  - go build

script:
  - go test -v ./...
  - ./bench.sh ./specious-db -entries 10000

addons:
  apt:
    packages:
      - libleveldb-dev
      - libleveldb1v5
